### PR TITLE
change the upload approval URl to the new uploader

### PR DESCRIPTION
**Pull request by peterneubauer**

### CODE REVIEW

**Comment by peterneubauer** [comment]
Don't merge this yet, the approval of multiple sequences is not yet ported to the new uploader.

**Comment by floscher** [comment]
This also has the same problem as #17: A [unit test](https://github.com/floscher/josm-mapillary-plugin/blob/master/test/unit/org/openstreetmap/josm/plugins/mapillary/utils/MapillaryURLTest.java#L77-L80) is [failing](https://travis-ci.org/floscher/josm-mapillary-plugin/jobs/153214637#L456).

**Comment by floscher** [comment]
@peterneubauer is this now obsolete, after 6b0794115199a884b581b9e84c1178074815a08b has been merged into `master`?

**Comment by peterneubauer** [comment]
True, closing this.

**Pull request closed without merging**
