### PR TITLE
updating traffic signs and image endpoints and graphics

### PR DESCRIPTION
**Pull request by peterneubauer**
This is an example, not fully updated with tests etc since I don't have the bandwidth right now. However, you should get the idea on how to retrieve images and trafficsign detections. Later, we can even add the real objects, see https://www.mapillary.com/developer/api-documentation/#the-map-object-feature but that will need a new UX layer since the objects are not at the same position as their (multiple) detections.

### CODE REVIEW

**Comment by peterneubauer** [comment]
@floscher anything I can do to help you adjusting the tests and merging? Seems people want to use the new detections :)

**Comment by floscher** [comment]
@peterneubauer I'll soon get to merging this.
There were some other changes since then, which I added first. The last one of these by the way being loading sequences over APIv3 :wink: .

**Comment by floscher** [comment]
@peterneubauer
For the map objects and detections, I've now chosen to implement this from scratch.
No offence, not because I disliked your changes. I rather tried to also add some other enhancements as well:
* separate JSON decoding from downloading
* thoroughly test the new code (the new code since v1.4.2 has ~72% code coverage, the JSON decoding code even 100%)
* cache the traffic sign icons locally
* implement the downloaders as `Runnable` instead of `Thread`s

Earlier today I created a pre-release [`v1.4.3-beta`](https://github.com/JOSM/Mapillary/releases/tag/v1.4.3-beta), which already contains a new Layer (`MapObjectLayer`). It displays all map objects (up to 500), which are inside the currently viewed part of the map. As of now this map object layer is not interactive. The pre-release now also downloads the image sequences via APIv3 and no longer cuts off the sequences at the borders of the `MapView`.
The detections are also in the works and will probably be included in the final v1.4.3 release. But for now I wanted to make the current state available for testing.

cc @nokutu
cc @PolyglotOpenstreetmap

**Comment by floscher** [comment]
I'm closing this now. The functionality is now integrated in the [version 1.5.0 of the plugin](https://github.com/JOSM/Mapillary/releases/tag/v1.5.0), which is now released.

**Pull request closed without merging**
