### PR TITLE
Move changesets and login to APIv3

### PR DESCRIPTION
**Pull request by peterneubauer**

### CODE REVIEW

**Comment by peterneubauer** [comment]
Hi there,
any feedback on this? Can I help in any way?

**Comment by floscher** [comment]
Unit tests [are](https://travis-ci.org/JOSM/Mapillary/jobs/237170885#L427) [failing](https://travis-ci.org/JOSM/Mapillary/jobs/237170885#L453).

Can you move the method [MapillaryURL.userURL()](https://github.com/JOSM/Mapillary/pull/58/files#diff-2219cfae09f8cdb73ea1bade61bb1f8fL166) into the [APIv3 class](https://github.com/JOSM/Mapillary/pull/58/files#diff-2219cfae09f8cdb73ea1bade61bb1f8fL21)?

Was the [removal of the IntelliJ code formatting settings](https://github.com/JOSM/Mapillary/pull/58/files#diff-f1045aea3015ed5f80704025e3ee300eL6) by accident or do they cause problems?

A nice to have would be to separate JSON-decoding (or in this case encoding) into a separate class. The other classes for JSON decoding for APIv3 are already in the package [`org.openstreetmap.josm.plugins.mapillary.utils.api`](https://github.com/JOSM/Mapillary/tree/0034a9aa2f8d6ae035432e771665906ee25d9d7b/src/org/openstreetmap/josm/plugins/mapillary/utils/api) backed by 98% unit test coverage.

**Comment by peterneubauer** [comment]
Ok, lemme work on that!

**Comment by floscher** [comment]
For me it's no problem, if they are removed. I'm normally working on this in Eclipse.
Some time ago I synced the settings as close as possible with the ones for Eclipse to avoid different formatting by Eclipse and IntelliJ users. So if you want to update the settings, that would also be fine.

I just wondered if this was intentional or e.g. automatically staged by the IDE.

**Comment by floscher** [comment]
I'll look into it later today and merge it.

**Comment by peterneubauer** [comment]
Thanks a lot @floscher !!

**Comment by floscher** [comment]
This has been merged as 751f4b758643f1ff515ed57ba9e0c4ada534323b...05efa4cf9a50b06d6451a989a3d63673cb8442bd

**Comment by peterneubauer** [comment]
Awesome, thanks @floscher @floscher !

**Pull request closed without merging**
